### ISSUE TITLE
Error submitting job with Torque

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise-client#14]
Using the new [BinAC specialization](https://github.com/MD-Studio/cerise-mdstudio-binac), I am trying to run the [gromit workflow](https://github.com/MD-Studio/cerise-mdstudio/blob/master/examples/run_gromacs.py) and I am getting the following error:
```
[2018-04-19 12:31:50.789] [CRITICAL] An internal error occurred when processing job c5bd998266854923a68a7
ea910ee0039 [cerise.back_end.execution_manager]
[2018-04-19 12:31:50.792] [CRITICAL] Traceback (most recent call last):
  File "cerise/../cerise/back_end/execution_manager.py", line 143, in _process_jobs
    self._stage_and_start_job(job_id, job)
  File "cerise/../cerise/back_end/execution_manager.py", line 100, in _stage_and_start_job
    self._job_runner.start_job(job_id)
  File "cerise/../cerise/back_end/xenon_job_runner.py", line 123, in start_job
    xenon_job = self._x.jobs().submitJob(self._sched, xenon_jobdesc)
jpype._jexception.nl.esciencecenter.xenon.jobs.InvalidJobDescriptionExceptionPyRaisable: nl.esciencecente
r.xenon.jobs.InvalidJobDescriptionException: torque adaptor: Torque adaptor cannot set STDOUT: a custom S
TDOUT is set internally
 [cerise.back_end.execution_manager]
```

Is this problem solve in Xenon 2.*?

**Comment by LourensVeen** [comment]
I don't think so, but I can probably work around it in Cerise. Early next week would be good I think?

**Comment by LourensVeen** [comment]
Actually, this is not a Cerise Client issue, it's a Xenon issue that causes Cerise to not work properly. See https://github.com/MD-Studio/cerise/issues/69. I'll close this one, as it's not Cerise Client that's the problem.
