### ISSUE TITLE
to_dict method

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise-client#6]
in the [example](https://github.com/MD-Studio/cerise-client/blob/develop/examples/example.py) the method `to_dict` is still used, but the new method is called `service_to_dict`

**Comment by LourensVeen** [comment]
Yes, the example needs to be updated still in general. Thanks for making an issue about it!

**Comment by felipeZ** [comment]
Also after stopping the service , the `start_managed_service` function must be called to restart the service

**Comment by LourensVeen** [comment]
Fixed in commit 632198f, released as part of version 0.2.1.
